-- 上层逻辑模块初始化
require "gamelogic.data.init"
require "gamelogic.attrblock.init"
require "gamelogic.errcode"
require "gamelogic.auxilary.init"
require "gamelogic.constant.init"
require "gamelogic.item.init"
require "gamelogic.template.init"
require "gamelogic.task.init"
