-- 任务
TASK_STATE_ACCEPT = 1 -- 接受
TASK_STATE_FINISH = 2 -- 完成

TASK_SCRIPT_SUSPEND = 1
TASK_SCRIPT_PASS = 2
TASK_SCRIPT_FAIL = 3
TASK_SCRIPT_NONE = 4

TASK_PLAY_FINDNPC = 1
TASK_PLAY_FINDITEM = 2
TASK_PLAY_NPCWAR = 3
TASK_PLAY_NONPCWAR = 4

