ITEMBAG_SPACE=100
ITEMPOS_BEGIN=21

BAG_NORMAL		= 1
BAG_FASHINOSHOW	= 2
BAG_CARD		= 3

EQUIPPOS_HAT = 1
EQUIPPOS_CLOAK = 2
EQUIPPOS_WEAPON = 3
EQUIPPOS_SHIELD = 4
EQUIPPOS_CLOTH = 5
EQUIPPOS_SHOE = 6
EQUIPPOS_NECKLACE = 7
EQUIPPOS_RING = 8
