--<<data_1500_GlobalTask 导表开始>>
data_1500_GlobalTask = {

	test = {
		task = "data_1500_TestTaskProcess",
		npc = "data_1500_TestTaskNpc",
		award = "data_1500_TestTaskAward",
		text = "data_1500_TestTaskText",
		fake = "nil",
		var = "nil",
		tasktype = 900,
		ringlimit = 0,
		donelimit = 0,
		interval = nil,
		isoverlay = 0,
		harddonelimit = 0,
		starttime = nil,
		endtime = nil,
		name = "测试",
		comment = "测试任务",
		desc = "这是测试任务的描述哦",
		awarddesc = "#<IR1>#数量可观,#<IR3>#数量可观",
		missiontype = 100,
		missionname = "测试任务",
		orderid = 1,
	},

	main = {
		task = "data_1500_MainTaskProcess",
		npc = "data_1500_MainTaskNpc",
		award = "data_1500_MainTaskAward",
		text = "data_1500_MainTaskText",
		fake = "nil",
		var = "data_1500_MainTaskVar",
		tasktype = 100,
		ringlimit = 0,
		donelimit = 0,
		interval = nil,
		isoverlay = 0,
		harddonelimit = 0,
		starttime = nil,
		endtime = nil,
		name = "主线",
		comment = "主线任务",
		desc = "这是主线任务的描述哦",
		awarddesc = "#<IR1>#数量可观,#<IR3>#数量可观",
		missiontype = 101,
		missionname = "剧情任务",
		orderid = 2,
	},

	branch = {
		task = "data_1500_BranchTaskProcess",
		npc = "data_1500_BranchTaskNpc",
		award = "data_1500_BranchTaskAward",
		text = "data_1500_BranchTaskText",
		fake = "nil",
		var = "nil",
		tasktype = 101,
		ringlimit = 0,
		donelimit = 0,
		interval = nil,
		isoverlay = 0,
		harddonelimit = 0,
		starttime = nil,
		endtime = nil,
		name = "支线",
		comment = "支线任务",
		desc = "这是支线任务的描述哦",
		awarddesc = "#<IR1>#数量可观,#<IR3>#数量可观",
		missiontype = 101,
		missionname = "剧情任务",
		orderid = 3,
	},

	shimen = {
		task = "data_1500_ShimenTaskProcess",
		npc = "data_1500_ShimenTaskNpc",
		award = "data_1500_ShimenTaskAward",
		text = "data_1500_ShimenTaskText",
		fake = "data_1500_ShimenTaskFake",
		var = "data_1500_ShimenTaskVar",
		tasktype = 102,
		ringlimit = 20,
		donelimit = 20,
		interval = "today",
		isoverlay = 0,
		harddonelimit = 0,
		starttime = nil,
		endtime = nil,
		name = "日常",
		comment = "协会请援",
		desc = "这是协会请援的描述哦",
		awarddesc = "#<IR1>#数量可观,#<IR3>#数量可观",
		missiontype = 102,
		missionname = "日常任务",
		orderid = 4,
	},

	shimoshilian = {
		task = "data_1500_ShiMoShiLianTaskProcess",
		npc = "data_1500_ShiMoShiLianTaskNpc",
		award = "data_1500_ShiMoShiLianTaskAward",
		text = "data_1500_ShiMoShiLianTaskText",
		fake = "data_1500_ShiMoShiLianTaskFake",
		var = "data_1500_ShiMoShiLianTaskVar",
		tasktype = 103,
		ringlimit = 10,
		donelimit = 100,
		interval = "today",
		isoverlay = 1,
		harddonelimit = 500,
		starttime = nil,
		endtime = nil,
		name = "日常",
		comment = "使魔试炼",
		desc = "这是使魔试炼的描述哦",
		awarddesc = "#<IR1>#数量可观,#<IR3>#数量可观",
		missiontype = 102,
		missionname = "日常任务",
		orderid = 5,
	},

	zhuanzhi = {
		task = "data_1500_ZhuanzhiTaskProcess",
		npc = "data_1500_ZhuanzhiTaskNpc",
		award = "data_1500_ZhuanzhiTaskAward",
		text = "data_1500_ZhuanzhiTaskText",
		fake = "nil",
		var = "nil",
		tasktype = 104,
		ringlimit = 0,
		donelimit = 0,
		interval = nil,
		isoverlay = 0,
		harddonelimit = 0,
		starttime = nil,
		endtime = nil,
		name = "转职",
		comment = "转职任务",
		desc = "这是转职任务的描述哦",
		awarddesc = "转职成功可获得新职业",
		missiontype = 101,
		missionname = "剧情任务",
		orderid = 6,
	},

	zhiyin = {
		task = "data_1500_ZhiyinTaskProcess",
		npc = "data_1500_ZhiyinTaskNpc",
		award = "data_1500_ZhiyinTaskAward",
		text = "data_1500_ZhiyinTaskText",
		fake = "nil",
		var = "data_1500_ZhiyinTaskVar",
		tasktype = 105,
		ringlimit = 0,
		donelimit = 0,
		interval = nil,
		isoverlay = 0,
		harddonelimit = 0,
		starttime = nil,
		endtime = nil,
		name = "指引",
		comment = "指引任务",
		desc = "这是指引任务的描述哦",
		awarddesc = "根据指引任务完成新手教学",
		missiontype = 103,
		missionname = "指引任务",
		orderid = 7,
	},

}
return data_1500_GlobalTask
--<<data_1500_GlobalTask 导表结束>>