require "gamelogic.attrblock.attrcontainer"
require "gamelogic.attrblock.basicattr"
require "gamelogic.attrblock.delaytonextlogin"
require "gamelogic.attrblock.switch"
require "gamelogic.attrblock.privatemsg"
require "gamelogic.attrblock.titledb"
require "gamelogic.attrblock.signin.init"
require "gamelogic.attrblock.chapterdb"
