data_0201_RoleSkillState = {
	[101] = {
		des = "昏迷",
		jinzhan_wugong = 1,
		yuancheng_wugong = 1,
		useSkill_jinzhan = 1,
		useSkill_yuancheng = 1,
		useSkill_fashu = 1,
		switchPos = 1,
		takeMedicine = 1,
		forceWugongTarget = 0,
		targetEffId = 0,
		immunStates = {},
	},

	[102] = {
		des = "石化",
		jinzhan_wugong = 0,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 0,
		useSkill_yuancheng = 0,
		useSkill_fashu = 0,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 0,
		targetEffId = 10003,
		immunStates = {},
	},

	[103] = {
		des = "冰冻",
		jinzhan_wugong = 0,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 0,
		useSkill_yuancheng = 0,
		useSkill_fashu = 0,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 0,
		targetEffId = 0,
		immunStates = {},
	},

	[104] = {
		des = "中毒",
		jinzhan_wugong = 0,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 0,
		useSkill_yuancheng = 0,
		useSkill_fashu = 0,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 0,
		targetEffId = 10003,
		immunStates = {},
	},

	[105] = {
		des = "沉默",
		jinzhan_wugong = 0,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 1,
		useSkill_yuancheng = 1,
		useSkill_fashu = 1,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 0,
		targetEffId = 10003,
		immunStates = {},
	},

	[106] = {
		des = "定身",
		jinzhan_wugong = 1,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 1,
		useSkill_yuancheng = 0,
		useSkill_fashu = 0,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 0,
		targetEffId = 10003,
		immunStates = {},
	},

	[107] = {
		des = "挑衅",
		jinzhan_wugong = 0,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 0,
		useSkill_yuancheng = 0,
		useSkill_fashu = 0,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 1,
		targetEffId = 10004,
		immunStates = {},
	},

	[108] = {
		des = "霸体",
		jinzhan_wugong = 0,
		yuancheng_wugong = 0,
		useSkill_jinzhan = 0,
		useSkill_yuancheng = 0,
		useSkill_fashu = 0,
		switchPos = 0,
		takeMedicine = 0,
		forceWugongTarget = 0,
		targetEffId = 0,
		immunStates = {101,105},
	},

}

