require "gamelogic.data.data_Huodong"
require "gamelogic.data.data_formula"
require "gamelogic.data.data_achievement"

require "gamelogic.data.data_language"
require "gamelogic.data.data_ResType"
require "gamelogic.data.data_GameID"
require "gamelogic.data.data_TemplAward"
require "gamelogic.data.data_RoGameSrvList"
require "gamelogic.data.data_RoWarSrvList"
require "gamelogic.data.data_RoCenterSrvList"

require "gamelogic.data.data_0101_CalculateHighLevelPro"
require "gamelogic.data.data_0101_Hero"
require "gamelogic.data.data_0301_TeamVar"
require "gamelogic.data.data_0301_TeamTarget"
require "gamelogic.data.data_0401_Map"
require "gamelogic.data.data_0501_ItemMaterial"
require "gamelogic.data.data_0501_ItemDrug"
require "gamelogic.data.data_0501_ItemBox"
require "gamelogic.data.data_0501_ItemBox_Award"
require "gamelogic.data.data_0501_ItemHat"
require "gamelogic.data.data_0501_ItemWeapon"
require "gamelogic.data.data_0501_ItemNecklace"
require "gamelogic.data.data_0501_ItemCloth"
require "gamelogic.data.data_0501_ItemCloak"
require "gamelogic.data.data_0501_ItemShield"
require "gamelogic.data.data_0501_ItemShoe"
require "gamelogic.data.data_0501_ItemRing"
require "gamelogic.data.data_0601_NPC"
require "gamelogic.data.data_0601_NPC_Button"
require "gamelogic.data.data_0701_Title"
require "gamelogic.data.data_0801_Refine"
require "gamelogic.data.data_0801_PromoteEquipVar"
require "gamelogic.data.data_0801_Fumo"
require "gamelogic.data.data_0801_FumoAttrRatio"
require "gamelogic.data.data_1001_LvExp"
require "gamelogic.data.data_1101_SignInCtrl"
require "gamelogic.data.data_1101_PerMonthSignIn"
require "gamelogic.data.data_GlobalTaskData"
require "gamelogic.data.data_TaskTest_Process"
require "gamelogic.data.data_TaskTest_Npc"
require "gamelogic.data.data_TaskTest_Award"
require "gamelogic.data.data_TaskTest_Text"

-- 别名
RESTYPE = data_ResType
