--<<data_0501_Map 导表开始>>
data_0501_Map = {

	[1] = {
		des = "小渔村",
		name = "东海渔村",
		needlv = 10,
		mapfile = "map01",
		minifile = "map01",
		width = 900,
		height = 680,
		block_width = 100,
		block_height = 80,
		music = "scene_1.mp3",
		strategy = 0,
		cankuafu = 1,
		caneasyleave = 1,
		warmap = 8,
	},

	[2] = {
		des = "长安城",
		name = "长安城",
		needlv = 20,
		mapfile = "maincity",
		minifile = "maincity",
		width = 900,
		height = 680,
		block_width = 100,
		block_height = 80,
		music = "scene_2.mp3",
		strategy = 0,
		cankuafu = 1,
		caneasyleave = 1,
		warmap = 9,
	},

	[3] = {
		des = "双叉岭",
		name = "双叉岭",
		needlv = 30,
		mapfile = "map03",
		minifile = "map03",
		width = 900,
		height = 680,
		block_width = 100,
		block_height = 80,
		music = "scene_1.mp3",
		strategy = 0,
		cankuafu = 1,
		caneasyleave = 1,
		warmap = 6,
	},

	[4] = {
		des = "长安郊外",
		name = "长安郊外",
		needlv = 40,
		mapfile = "map04",
		minifile = "map04",
		width = 900,
		height = 680,
		block_width = 100,
		block_height = 80,
		music = "scene_1.mp3",
		strategy = 0,
		cankuafu = 1,
		caneasyleave = 1,
		warmap = 1,
	},

	[5] = {
		des = "火焰山",
		name = "火焰山",
		needlv = 50,
		mapfile = "map05",
		minifile = "map05",
		width = 900,
		height = 680,
		block_width = 100,
		block_height = 80,
		music = "scene_10.mp3",
		strategy = 0,
		cankuafu = 1,
		caneasyleave = 1,
		warmap = 2,
	},

	[6] = {
		des = "方寸山",
		name = "方寸山",
		needlv = 60,
		mapfile = "map06",
		minifile = "map06",
		width = 900,
		height = 680,
		block_width = 100,
		block_height = 80,
		music = "scene_11.mp3",
		strategy = 0,
		cankuafu = 1,
		caneasyleave = 1,
		warmap = 13,
	},

}
return data_0501_Map
--<<data_0501_Map 导表结束>>